service: sls-crud

provider:
    name: aws
    runtime: nodejs16.x
    stage: dev
    region: us-west-1
    environment:
        DYNAMODB_TABLE_NAME: ${self:custom.usersTableName}
        WS_SERVICE_URL:
            Fn::Join:
                - ""
                - - Ref: WebsocketsApi
                  - .execute-api.
                  - Ref: AWS::Region
                  - .amazonaws.com/
                  - ${self:provider.stage}

custom:
    usersTableName: dm2-crud-users-tbl-${self:provider.stage}
    serverless-offline:
        resourceRoutes: true

plugins:
    - serverless-iam-roles-per-function
    - serverless-dotenv-plugin
    - serverless-plugin-typescript
    - serverless-tscpaths
    - serverless-offline

resources:
    Resources:
        UsersTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.usersTableName}
                AttributeDefinitions:
                    - AttributeName: PK
                      AttributeType: S
                    - AttributeName: SK
                      AttributeType: S
                KeySchema:
                    - AttributeName: PK
                      KeyType: HASH
                    - AttributeName: SK
                      KeyType: RANGE
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1

functions:
    - ${file(sls-functions/restful.yml)}
    - ${file(sls-functions/websocket.yml)}
